### ISSUE TITLE
Getting Crash on App opening

### ISSUE THREAD

**Issue by abhijitsrivastava** [davidgatti/dgCam#5]
09-09 16:28:44.384  22728-22728/pl.gatti.dgcam E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: pl.gatti.dgcam, PID: 22728
    java.lang.RuntimeException: Unable to resume activity {pl.gatti.dgcam/pl.gatti.dgcam.DgCamActivity}: java.lang.RuntimeException: setParameters failed
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2995)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3030)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2393)
            at android.app.ActivityThread.access$800(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
     Caused by: java.lang.RuntimeException: setParameters failed
            at android.hardware.Camera.native_setParameters(Native Method)
            at android.hardware.Camera.setParameters(Camera.java:1876)
            at pl.gatti.dgcam.DgCamActivity.createCamera(DgCamActivity.java:118)
            at pl.gatti.dgcam.DgCamActivity.onResume(DgCamActivity.java:157)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1264)
            at android.app.Activity.performResume(Activity.java:6039)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2978)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3030)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2393)
            at android.app.ActivityThread.access$800(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by davidgatti** [comment]
@abhijitsrivastava what a surprise, after so many years :) someone did something on this project :D 

About this issue, as you can see the issue is with `setParameters`. Sadly some Android devices won't accept some parameters that are actually in the Android documentation. 

To circumvent this issue, you can check first with a `if()` is this parameter exists or can be set. If not, just keep going with the code.

Does this help?
